"""added emptype

Revision ID: 11fa05b9766e
Revises: 406c3a2ca9d6
Create Date: 2024-07-10 10:18:09.255375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fa05b9766e'
down_revision = '406c3a2ca9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Emp_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('Emp_type')

    # ### end Alembic commands ###
