"""updated assets

Revision ID: 366972f8028e
Revises: 
Create Date: 2024-08-30 12:56:26.397255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366972f8028e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('issue_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('return_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('return_date')
        batch_op.drop_column('issue_date')
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
