"""Query status changed which is New

Revision ID: 7584aed44f15
Revises: c84b5d46d324
Create Date: 2025-06-04 11:59:53.922820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7584aed44f15'
down_revision = 'c84b5d46d324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('signup_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_id', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
