"""removed Nominee

Revision ID: 7e3f75a0887b
Revises: f2e889a389de
Create Date: 2024-07-23 12:31:14.254240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e3f75a0887b'
down_revision = 'f2e889a389de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_details', schema=None) as batch_op:
        batch_op.drop_column('nominee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nominee', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###
