"""Query changes

Revision ID: 83edf8ae0c87
Revises: 3cc575e3f02f
Create Date: 2024-09-05 16:49:21.579705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83edf8ae0c87'
down_revision = '3cc575e3f02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
