"""update leave model

Revision ID: 89f5127c1854
Revises: 83edf8ae0c87
Create Date: 2024-09-17 11:28:52.556398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89f5127c1854'
down_revision = '83edf8ae0c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.String(length=255), nullable=False))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('leave_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leave_days', mysql.FLOAT(), nullable=False))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
