"""Remove unique constraint from admin_id in education table

Revision ID: ab50c96288d1
Revises: 7e3f75a0887b
Create Date: 2024-07-24 16:16:09.176745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab50c96288d1'
down_revision = '7e3f75a0887b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_doc', schema=None) as batch_op:
        batch_op.drop_index('admin_id')

    op.drop_table('upload_doc')
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_index('admin_id')

    with op.batch_alter_table('upload_docs', schema=None) as batch_op:
        batch_op.drop_index('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload_docs', schema=None) as batch_op:
        batch_op.create_index('admin_id', ['admin_id'], unique=True)

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.create_index('admin_id', ['admin_id'], unique=True)

    op.create_table('upload_doc',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doc_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('doc_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('issue_date', sa.DATE(), nullable=False),
    sa.Column('doc_file', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name='upload_doc_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('upload_doc', schema=None) as batch_op:
        batch_op.create_index('admin_id', ['admin_id'], unique=True)

    # ### end Alembic commands ###
