"""Added signup_id to LeaveBalance

Revision ID: bd5bfb19dcd8
Revises: 
Create Date: 2025-02-10 11:55:48.155916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd5bfb19dcd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('circle', sa.String(length=50), nullable=False),
    sa.Column('emp_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_id', sa.Integer(), nullable=False))
        batch_op.alter_column('privilege_leave_balance',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('casual_leave_balance',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['signup_id'])
        batch_op.drop_constraint('leave_balances_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'signups', ['signup_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('leave_balances_ibfk_1', 'admins', ['admin_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('casual_leave_balance',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('privilege_leave_balance',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('signup_id')

    op.drop_table('payslips')
    op.drop_table('news_feeds')
    # ### end Alembic commands ###
