"""privilage leave model

Revision ID: cee41d03a4fa
Revises: a8bda0737dd2
Create Date: 2024-09-17 12:26:35.833969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cee41d03a4fa'
down_revision = 'a8bda0737dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('privilege_leave_balance', sa.Float(), nullable=True))
        batch_op.drop_column('personal_leave_balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_balances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_leave_balance', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('privilege_leave_balance')

    # ### end Alembic commands ###
